### ISSUE TITLE
Can't check transaction related to state channels

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-goggles#24]
I'm using testnet.goggles.aepps.com to check this transaction:
> tx_+NkLAfhCuECIIeWttRUiZ32uriBdmM1t+dCg90KuG2ABxOiuXqzpAul6uTWvsyfx3EFJDah6trudrityh+6XSX3mkPEimhgGuJH4jzIBoQELtO15J/l7UeG8teE0DRIzWyorEsi8UiHWPEvLOdQeYYgbwW1nTsgAAKEB6bv2BOYRtUYKOzmZ6Xcbb2BBfXPOfFUZ4S9+EnoSJcqIG8FtZ07IAACIAWNFeF2KAAAKAIYSMJzlQADAoDBrIcoop8JfZ4HOD9p3nDTiNthj7jjl+ArdHwEMUrvQgitwOr/v3Q==

It sticks on loading indication with an exception:
> Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at d (validator.js:128)
    at Object.h [as verifyTx] (validator.js:145)
    at Object.p [as unpackAndVerify] (validator.js:114)
    at a.validate (App.vue:138)
    at e (vue.runtime.esm.js:2132)
    at HTMLButtonElement.t._withTask.t._withTask (vue.runtime.esm.js:1917)

in developer console

**Comment by VladislavIvanov** [comment]
Hi @davidyuk, 
Thanks for the issue. It is addressed and will be adjust with the next release of the js-sdk.

**Comment by HristiyanG** [comment]
Should be fixed in aepp-sdk-js PR: #496

**Comment by maptuhec** [comment]
New release of the https://goggles.aepps.com/ is available with the fix. I will close the issue
